services:
  # first-instance-db:
  #   image: postgres:14.2-alpine
  #   container_name: first-instance-db
  #   ports:
  #     - 5431:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: Planet9
  #   volumes:
  #     - first-instance-db-data:/var/lib/postgresql/data
  #     - ./init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql
  #   restart: unless-stopped
  #   healthcheck:
  #     test: 'pg_isready -U postgres'
  #   networks:
  #     - local_net

  # second-instance-db:
  #   image: postgres:14.2-alpine
  #   container_name: second-instance-db
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: Planet9
  #   volumes:
  #     - second-instance-db-data:/var/lib/postgresql/data
  #     - ./init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql
  #   restart: unless-stopped
  #   healthcheck:
  #     test: 'pg_isready -U postgres'
  #   networks:
  #     - local_net

  neptune-first-instance:
    image: neptunesoftware/planet9:v23.10.7
    container_name: neptune-first-instance
    environment:
      PORT: 9101
    # depends_on:
    #   - first-instance-db
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - local_net

  neptune-second-instance:
    image: neptunesoftware/planet9:v23.10.7
    container_name: neptune-second-instance
    environment:
      PORT: 9100
    # depends_on:
    #   - second-instance-db
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - local_net

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/smart-watering.xyz/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/smart-watering.xyz/privkey.pem:/etc/ssl/private/privkey.pem
      - /etc/letsencrypt/live/second.smart-watering.xyz/fullchain.pem:/etc/ssl/certs/second/fullchain.pem
      - /etc/letsencrypt/live/second.smart-watering.xyz/privkey.pem:/etc/ssl/private/second/privkey.pem
    depends_on:
      # - first-instance-db
      # - second-instance-db
      - neptune-first-instance
      - neptune-second-instance
    networks:
      - local_net
    restart: unless-stopped
    command: ["nginx", "-g", "daemon off;"]

# volumes:
#   second-instance-db-data: {}
#   first-instance-db-data: {}

networks:
  local_net:
    driver: bridge